baseurl = "ronghua.cn"
title = "RONGHUALI PAGE"
theme = "hugo-coder"
languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"


[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # This allows HTML in markdown
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[markup.highlight]
style = "github-white"

[params]
  author = "RONGHUA LI"
  info = "Study Records"
  description = "RONGHUA LI's personal website"
  keywords = "blog,study,personal"
  avatarurl = "/images/avatar.jpg"

  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2025


  math = true  # Enable math support

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ronghua-li/"
# 可用的图标来自Font Awesome，支持多种社交平台。

# Menu links
[[menu.main]]
  name = "Research"
  weight = 1
  url  = "researches/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "blogs/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"